config/routes.rb
Attorney::Application.routes.draw do
  resources :inquiries, :only => [:new, :create] do
  get 'thank_you', :on => :collection
end
  
 
   root  'static_pages#home'
   match '/law',   to: 'static_pages#law',   via: 'get'
   match '/contact' , to: 'inquiries#new', via: 'get'

   match '/university', to: 'static_pages#university', via: 'get' 
     
   match 'base', to: 'reference_pages#base', via: 'get'
   match 'work', to: 'reference_pages#work', via: 'get'
   match 'office', to: 'reference_pages#office', via: 'get'
   match 'article', to: 'reference_pages#article', via: 'get'
   
   match 'officea', to: 'introduction_pages#officea', via: 'get'
   match 'officeb', to: 'introduction_pages#officeb', via: 'get'
   match 'basea', to: 'introduction_pages#basea', via: 'get'
   match 'baseb', to: 'introduction_pages#baseb', via: 'get'
   match 'worka', to: 'introduction_pages#worka', via: 'get'

   match 'officeatest', to: 'test_pages#officeatest', via: 'get'
   match 'officebtest', to: 'test_pages#officebtest', via: 'get'
   match 'baseatest', to: 'test_pages#baseatest', via: 'get'
   match 'basebtest', to: 'test_pages#basebtest', via: 'get'
   match 'worktest', to: 'test_pages#worktest', via: 'get'
   

   

  

end

app/models/inquiry.rb
class Inquiry
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations
  include ActionView::Helpers::TextHelper
  
  attr_accessor :name, :email, :message, :nickname
  
  validates :name, 
            :presence => { :message => "نمیتواند خالی باشد" }
  
  validates :email,
            :presence => { :message => "نمیتواند خالی باشد" },
            :format => { :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/, :message=> "معتبر نمیباشد" }
  
  validates :message,
            :length => { :minimum => 10, :maximum => 1000, :message => "حداقل ۱۰ کاراکتر میباشد" }
            
  #validates :nickname, 
            #:format => { :with => /^$/ }
          HUMANIZED_ATTRIBUTES = {
:name => "نام و نام خوانوادگی",
:email=> "پست الکترونیکی",
:message => "پیغام"
}
 def self.human_attribute_name(attr, options={})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
end 

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def deliver
    return false unless valid?
    Pony.mail({
      :from => %("#{name}" <#{email}>),
      :reply_to => email,
      :subject => "Website inquiry",
      :body => message,
      :html_body => simple_format(message)
    })
  end
      
  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  
  def new
    @inquiry = Inquiry.new
  end
    
  def create
    @inquiry = Inquiry.new(params[:inquiry])
    if @inquiry.deliver
      render :thank_you
    else
      render :new
    end
  end
  
end

app/controllers/introduction_pages_controller.rb
class IntroductionPagesController < ApplicationController
  def officea
  end

  def officeb
  end

  def basea
  end

  def baseb
  end

  def worka
  end
end

app/controllers/reference_pages_controller.rb
class ReferencePagesController < ApplicationController
  def office
  end

  def base
  end

  def work
  end
  
  def article
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def law
  end

  def university
  end

  def contact
  end

  
end

app/controllers/test_pages_controller.rb
class TestPagesController < ApplicationController
  def baseatest
  end

  def basebtest
  end

  def officeatest
  end

  def officebtest
  end

  def worktest
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/introduction_pages_helper.rb
module IntroductionPagesHelper
end

app/helpers/reference_pages_helper.rb
module ReferencePagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/test_pages_helper.rb
module TestPagesHelper
end

app/views/inquiries/_form.html.erb
  <h3 dir="rtl" >        اطلاعات تماس:</h3>
<p dir="rtl">  آدرس دفتر:           مشهد، بلوارمدرس (دروازه طلایی) ، نبش مدرس ۸<br>ساختمان مدرس، طبقه چهارم واحد ۴  <br>
  ساعات کار: شنبه تا چهارشنبه ۵ تا ۷ بعد از ظهر <br>
تلفن: ۰۵۱۱۲۲۵۶۴۷۳  
<br>تلفاکس: ۰۵۱۱۲۲۵۱۵۶۰ 
<br>همراه: ۰۹۱۵۳۱۳۹۸۲۲ 
<br> پست الکترونیکی: abasshahravan@gmail.com  </p>

                     <div class = "english">
                    <h2> Contact Us: </h2>
                    <p>No.4, 4th Floor, Modarres Buld, Modarres Blvd, Mashhad-Iran <br>
  Tel: +98-511-2256473 <br>
  Tel & fax: +98-511- 2251560<br>
  Mob: +98-915 313 9822 <br>
  Working days are: Sat-Wed 5p.m to 7p.m <br>
  email: abasshahravan@gmail.com 
</div>

  

app/views/inquiries/new.html.erb
<%= render 'form', :inquiry => @inquiry %>

app/views/inquiries/thank_you.html.erb
<p dir = "rtl"> با سلام پیغام شما دریافت شد.</p>

app/views/introduction_pages/basea.html.erb
<p dir = "rtl">تعداد واحد :۲ <br>
نوع واحد: نظری <br>
<strong>پیش نیاز: ندارد</strong> <br>
ساعات درس: ۳۲ ساعت <br>
هدف : آشنا ساختن دانشجویان با تاریخ تحولات و مبانی حقوق اساسی و همچنین شناساندن مفاهیم دولت، حکومت، رژیم های سیاسی و ارتباط بین قوای مقننه، مجریه و قضاییه . <br>
<h3 dir = "rtl">سرفصل دروس: </h3>
<h3 dir = "rtl">بخش اول: تاریخ تحولات و مبانی حقوق اساسی </h3>
<p dir = "rtl">۱- حقوق اساسی چیست؟       <br>       	۲-  تعریف <br>
۳- تطور			<br>		۴- موضع حقوق اساسی در میان سایر رشته های حقوق عمومی <br>
۵- رابطه حقوق اساسی با سایر رشته های نظیر فلسفه ،تاریخ ،جامعه شناسی و نظایر آنها <br>
۶- منابع و روش ها <br>
<h3 dir = "rtl">بخش دوم: دولت </h3>
<p dir = "rtl">۱- تعریف و مفاهیم دولت	<br>		۲- نظریات فلسفی درباره دولت <br>
۳- نظریات حقوقی مختلف از نویان تا حال حاضر درباره دولت <br>
۴- نظریات اسلامی درباره مفهوم ملت، امت ،کشور ، سرزمین ،دولت و عوامل تشکیل دهنده حاکمیت و مقایسه با دیگر نظریات <br>
<h3 dir = "rtl">بخش سوم: رژیم های سیاسی </h3>
<p dir = "rtl">۱- بررسیهای پایه ای    	<br>		۲- نظریات مجموعی <br>
۳- طبقه بندی انواع نظریات اصحاب رأی و فن، ذکر مثال از کشورهای مختلف <br>
<h3 dir = "rtl">بخش چهارم: حکومت </h3>
<p dir = "rtl">۱- تعریف حکومت <br>
۲- قوه مقننه، قوه مجریه( هیأت دولت، رییس مملکت، کارکنان دولت) و قوه قضائیه در ارتباط با بنیان های حکومتی  <br>
<h3 dir = "rtl">بخش پنجم:  نظامهای بزرگ حقوق اساسی  </h3>
<p dir = "rtl">۱-  نظامهای بزرگ حقوق اساسی کشورهای با دموکراسی لیبرال <br>
۲- کشورهای اقتدارگر، نظامهای فاشیستی، نظامهای سوسیالیستی و تقسیمات درونی هر کدام  <br>
۳- حقوق و آزادیهای فردی، حقوق متقابل فرد و دولت از جمله با توجه به دیدگاه اسلام.

app/views/introduction_pages/baseb.html.erb
<p dir = "rtl">تعداد واحد:۳ <br>
نوع واحد: نظری <br>
<strong>پیش نیاز : حقوق اساسی ۱</strong> <br>
ساعات درس: ۴۸ ساعت <br>
هدف: آشنا ساختن دانشجویان با تاریخ و مبانی حقوق اساسی ایران، آموزش مبانی فکری و عقیدتی تدوین قانون اساسی جمهوری اسلامی ایران و همچنین تدریس این قانون و مصوبات موجود کشور در ارتباط با حقوق اساسی و بالاخره عملکردهای نهادهای سیاسی و حقوقی جمهوری اسلامی .
<br>
<h3 dir = "rtl">سرفصل دروس: <br><br>
بخش اول: تاریخچه و مبانی حقوق اساسی ایران </h3>
<p dir = "rtl">۱- خطوط کلی قوانین اساسی ۱۲۸۵ و ۱۲۸۶ <br>
۲- نظریات تحلیلی و نقادانه از قوانین گذشته <br>
<h3 dir = "rtl">بخش دوم: مبانی اعتقادی درتدوین قانون اساسی جمهوری اسلامی ایران</h3>
<p dir = "rtl">۱- مبانی اعتقادی اسلامی <br>
۲- مسئله ولایت فقیه وتبدیل این اصل به نهادهای سیاسی موجود  <br>
۳- مسئله نظام اقتصادی (مالکیت ، اموال عمومی، تعاون، بیمه ها و نظایر آن) <br>
۴-رهبر، رییس جمهور، ، هیأت وزیران، مجلس شورای اسلامی، شورای نگهبان، دیوان عدالت اداری، دادگاهها و نهادهای دیگر مندرج در قانون اساسی <br>
۵- چگونگی تفکیک قوا، نحوه ارتباط بین سه قوه، نحوه مدیریت بنیانی نهادها <br>
۶- در ضمن به بررسی مقایسه ای از رژیم گذشته از حیث حقوقی و نقاط اشتراک و افتراق این رژیم با سایر رژیمهای حقوقی سایر کشورها پرداخته خواهد شد. <br>

app/views/introduction_pages/officea.html.erb
<p dir = "rtl">تعداد واحد: ۲ <br>
نوع واحد: نظری <br>
<strong>پیش نیاز : ندارد </strong> <br>
ساعات درس: ۳۲ ساعت <br>
هدف: آشنا ساختن دانشجویان با مفاهیم کلی حقوق اداری <br></p>
<h3 dir = "rtl">سرفصل دروس: </h3>
<h3 dir = "rtl">بخش اول: کلیات </h3>
<p dir="rtl">۱- تعریف اداره <br>
۲- جایگاه حقوق اداری <br>
<h3 dir = "rtl">بخش دوم: </h3>
<p dir = "rtl">۱-  مبانی حقوق اداری( نظریه خدمات عمومی ، منافع عمومی، قدرت عمومی) <br>
۲- منابع حقوق اداری (قانون، آیین نامه، رویه قضائی، اندیشه های حقوقی) <br>
۳- اشخاص حقوقی ( اشخاص حقوق عمومی، اشخاص حقوق خصوصی و وجوه تمایز آنها) <br>
۴- اصول حاکم بر سازمانهای اداری (تمرکز و عدم تمرکز اداری)<br>
۵- نظارت در حقوق اداری<br>
۶- مقامات مرکزی (رهبر، رییس جمهور، معاونین رئیس جمهور، وزراء)<br>
۷- سلسله مراتب اداری<br>
۸- سازمانهای مرکزی (وزارتخانه ها، نهادها و...)<br>
۹- تقسیمات کشوری<br>
۱۰- سازمانهای اداری غیرمتمرکز(شوراها...)<br>
۱۱- سازمانهای اداری مستقل (مؤسسات عمومی ، خیریه، حرفه ای...)<br>
۱۲- بازرسی کل کشور<br>
۱۳- دیوان عدالت اداری (تشکیلات، صلاحیت ، حدود و اختیارات ، نحوه رسیدگی...) </p>

app/views/introduction_pages/officeb.html.erb
<p dir= "rtl">تعداد واحد:۲ <br>
نوع واحد: نظری <br>

<strong>پیش نیاز: حقوق اداری ۱</strong> <br>
ساعات درس: ۳۲ ساعت <br>
هدف: آشنا ساختن دانشجویان با استخدام کشوری در جمهوری اسلامی ایران، حقوق و تکالیف مأموران دولتی، مقررات استخدامی خاص و قراردادهای اداری <br>
<h3 dir = "rtl">سرفصل دروس: </h3>
<h3 dir = "rtl">بخش اول: استخدام کشوری </h3>
<p dir= "rtl">۱- مفاهیم و تعاریف استخدام عمومی <br>
۲- ترکیب مأموران به خدمات عمومی و ماهیت استخدام<br>
۳- مسایل عمومی استخدام<br>
۴- تشکیلات استخدام در جمهوری اسلامی ایران<br>
۵- طبقات شغلی<br>
۶- ورود و خروج از خدمات دولتی<br>
۷- حقوق و مزایای مستخدمین دولتی<br>
۸- تکالیف مستخدمین دولتی<br>
۹- مقررات استخدامی خاص(شهرداری ، وزرات امور خارجه...)<br>
۱۰- قراردادهای اداری<br> </p>

app/views/introduction_pages/worka.html.erb
<p dir = "rtl">تعداد واحد:۲	 <br>						
<strong>پیش نیاز : حقوق جزای عمومی ۲ </strong> <br>
ساعات درس: ۳۲ ساعت <br>
هدف: آشنا ساختن دانشجویان با حقوق و مقررات کار که تنظیم کننده روابط بین کارگران و کارفرمایان کشور است .<br>

<h3 dir = "rtl">سرفصل دروس <br><br>
بخش اول: کلیات </h3> 
<p dir = "rtl">۱- بررسی تحول روابط کار قبل از انقلاب صنعتی و پس از آن و مطالعه علل وضع قوانین کار <br>
۲- دیدگاه مکاتب مختلف درباره کار <br>
۳- کار و ارزش آن از نظر حقوق اسلامی (انواع کار و احکام آن، حقوق و امتیازات کارگر) <br>
۴- تعریف و مشخصات حقوق کار <br>
<h3 dir = "rtl">بخش دوم: منابع </h3>
<p dir = "rtl">۱-  منابع حقوق کار <br>
۲- قرارداد کار(تحول تاریخی و نقش فعلی آن، وجوه تمایز آن از سایر قراردادها، شرایط اساسی انعقاد آن، بطلان، تجدیدنظرو تعلیق آن، انحلال آن و مسایل مربوط به اخراج کارگر) <br>
<h3 dir = "rtl">بخش سوم: حقوق و تعهدات کارگر </h3>
<p dir = "rtl">۱-  ساعات کار ، تعطیلات و مرخصی سالیانه	 <br>	۲- شرایط کار زنان <br>
۳- شرایط کار نوجوانان <br>
۴-مزد (مفهوم آن، روشهای تعیین مزد و عوامل موثر در آن، طبقه بندی مشاغل به نظام حقوقی کار) <br>
۵- تعهدات کارگر <br>
<h3 dir = "rtl">بخش چهارم: حقوق و تکالیف کارفرما (از جمله موارد مسئولیت کیفری کارفرما) </h3>
<h3 dir = "rtl">بخش پنجم: نظارت </h3>
<p dir = "rtl">۱- بهداشت کارگاه و حفاظت فنی کارگران	 <br>	۲- بازرسی کار و نقش وزارت کار <br>
<h3 dir = "rtl">بخش  ششم: حل و فصل اختلافات </h3>
<p dir = "rtl">۱- مراجع رسیدگی به اختلافات بین کارگر و کارفرما (شورای کارگاه، هیأت حل اختلاف، هیأت عالی حل اختلاف) بر اساس قوانین کار موجود.

app/views/layouts/_footer.html.erb
<div id="footer">
	
    
    
  </div>
</div>
<div align=center>This template  downloaded form <a href='http://all-free-download.com/free-website-templates/'>free website templates</a></div> <br>
<div align=center> Converted by <a href='http://pcprotego.fi'> PcProtego </a>2013</div>

app/views/layouts/_header.html.erb
<div id="wrapper">
  <div id="header">
    <div id="logo">
      <!<h1><!<a href="#"><!<span><!</span><!</a><!</h1>
    </div>
    <div class="clr"></div>
  </div>
  <div class="content">
    <ul id="menu">
     
      <li><%= link_to "صفحه اصلی",    root_path %></li>
      <li><%= link_to "امور وکالتی",    law_path %></li>
      <li><%= link_to "امور دانشگاهی",    university_path %></li>
      
      <li><%= link_to "(en)اطلاعات تماس",    contact_path %></li>

      

    </ul>

    <div id="pitch">
      <h3 dir="rtl"><strong>عباس شهروان  </strong> </h3><br><h1 dir="rtl">  وکیل پایه یک دادگستری 
                  <br>عضو هیات علمی دانشکده حقوق<br /><br> 
                  <h2 dir= "rtl"><strong>Abas Shahravan </strong> <br>
                  Attorney at Law <br>
                  Member of Law Department of University </h2>


        </h1>
      <p><em> </em></p>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Lawyer &amp; Attorney</title>
<%= stylesheet_link_tag    "application", media: "all",
                                            "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<link rel="stylesheet" type="text/css" href="css/screen.css" media="screen" />
</head>

<body>
	<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>


</body>
</html>

app/views/reference_pages/base.html.erb
<p dir = "rtl">۱-حقوق اساسی              -                                      بوشهری ، جعفر <br>	
۲- حقوق اساسی                             -                      طباطبایی مؤتمنی ، منوچهر  <br>	
۳- حقوق اساسی                              -                      قاسم زاده، قاسم   <br>	
۴- حقوق اساسی                               -                     قراچورلو، رزا <br>	
۵- حقوق اساسی                                -                    هکی، فرشید  <br>	
۶- حقوق اساسی ۱                               -                  اسعدی ، میثم  <br>	
۷- حقوق اساسی ۱                                -                 خسروی ،حسن   <br>	 
۸- حقوق اساسی ۲                                 -                 خسروی، حسن  <br>	   
۹- حقوق اساسی ایران                              -             عمید زنجانی، عباسعلی <br>	
۱۰- حقوق اساسی                                     -              دولتی پتهرشت، مهدی <br>	
۱۱- حقوق اساسی تطبیقی                               -          مدنی ، جلال الدین <br>	
۱۲- حقوق اساسی تطبیقی                                -         عمید زنجانی، عباسعلی  <br>	  
۱۳- حقوق اساسی تطبیقی                                 -        هریسی نژاد، کمال<br>	
۱۴- حقوق اساسی جمهوری اسلامی ایران                     - هاشمی، محمد<br>	

app/views/reference_pages/office.html.erb
<p dir = "rtl">۱- حقوق اداری            -                                   طباطبایی مؤتمنی، منوچهر <br>
 ۲- حقوق اداری                            -                 مدنی، جلال الدین    <br>       
 ۳- حقوق اداری                             -                امامی، محمد   <br>
 ۴- حقوق اداری                              -               عباسی لاهیجی، بیژن <br>   
 ۵- حقوق اداری                                -             موسی زاده، ابراهیم   <br> 
 ۶- حقوق اداری ۱                               -        رضایی زاده، محمد جواد <br>   
۷- حقوق ادری ۱ و ۲ کلیات و ایران                 - موسی زاده ، رضا    <br> 
۸- حقوق اداری افغانستان                            -    محمدی نمکی، عبدالعلی <br>     
۹- حقوق اداری ایران استخدام های کشوری     -    ابوالحمد، عبدالحمید  <br>    
۱۰- حقوق اداری تطبیقی                       -           هداوند، مهدی   <br>      
۱۱- حقوق اداری تطبیقی                        -          طباطبایی مؤتمنی، منوچهر <br>   
۱۲- حقوق اداری                                -            قراچورلو، رزا<br>
۱۳- حقوق اداری                                 -        استوار سنگری، کورش و                                                                                   امامی، محمد					

app/views/reference_pages/work.html.erb
    <p dir = "rtl">۱- یکصد قانون طلایی کار    -    تمپلر،ریچارد (ترجمه: ژروین،شهلا) <br>
    ۲- طبقه بندی مشاغل از دیدگاه قانون کار    -     کرم بیگی ،ابوالقاسم <br>
    ۳- حقوق کار                         -                   عراقی ، عزت ا... <br>
     ۴- حقوق کار ایران                    -                نیاکی،جعفر <br>
     ۵- تاریخچه و سیر تحول حقوق کار        -        هاشمی ،سید محمد <br>
     ۶- حقوق بین المللی کار                -               عراقی ، عزت ا... <br>
      ۷- قانون کار در نظم حقوقی کنونی      -           طاهری ، محمد  سلمان <br>
      ۸- راهنمای قانون کار                 -                 معدنی ، مژگانه <br>
      ۹- قانون کار ، تأمین اجتماعی و بیمه بیکاری    -    قشقایی ، محمد حسین <br>
       ۱۰- قانون کار                     -                      رضا زاده ملک ، رحیم <br>
      ۱۱- حقوق کار                      -                      رنجبری ، ابوالفضل <br>
       ۱۲- حقوق کار                       -                    احمدی، سید احمد <br>
       ۱۳- قراردادکار                      -                    زفرقندی، محمد <br>
       ۱۴- حقوق کار و نحوه رسیدگی شکایات    -       اباذری فومنی، منصور  <br>

app/views/static_pages/contact.html.erb
<h3 dir="rtl" >        اطلاعات تماس:</h3>
<p dir="rtl">  آدرس دفتر:           مشهد، بلوارمدرس (دروازه طلایی) ، نبش مدرس ۸<br>ساختمان مدرس، طبقه چهارم واحد ۴  <br>
	ساعات کار: شنبه تا چهارشنبه ۵ تا ۷ بعد از ظهر <br>
تلفن: ۰۵۱۱۲۲۵۶۴۷۳  
<br>تلفاکس: ۰۵۱۱۲۲۵۱۵۶۰ 
<br>همراه: ۰۹۱۵۳۱۳۹۸۲۲ 
<br> پست الکترونیکی: abasshahravan@yahoo.com  </p>
<figure class="img-border">
											<iframe width="400" height="260" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/?ie=UTF8&amp;ll=36.300185,59.607182&amp;spn=0.079549,0.157928&amp;t=m&amp;z=13&amp;output=embed"></iframe>
										</figure> <br><br><br><br><br><br><br><br>
										<h2> Contact Us: </h2>
										<p>No.4, 4th Floor, Modarres Buld, Modarres Blvd, Mashhad-Iran <br>
	Tel: +98-511-2256473 <br>
	Tel & fax: +98-511- 2251560<br>
	Mob: +98-915 313 9822 <br>
	Working days are: Sat-Wed 5p.m to 7p.m <br>
	email: abasshahravan@yahoo.com


	

app/views/static_pages/home.html.erb
<div class="col">
      <h3 dir = "rtl">اطلاعات تماس:</h3>
      <p dir = "rtl">نحوه ارتباط</p>
      <a class = "link" <%= link_to "اطلاعات بیشتر",    contact_path %> 
       </div>
       
    <div class="col">
      <h3 dir = "rtl">امور دانشگاهی:</h3>
      <p dir = "rtl"> معرفی سر فصل دروس،منابع درسی و نمونه سؤالات</p>
      <a class = "link" <%= link_to "اطلاعات بیشتر",    university_path %> </a></div>
    <div class="col last">
      <h3 dir = "rtl">امور وکالتی:</h3>
      <p dir = "rtl">دعاوی ملکی</p>
       <a class = "link" <%= link_to "اطلاعات بیشتر",    law_path %> </a> </div>
    <div class="clr"></div>
  </div>
    <div class="clr"></div>
  </div>

app/views/static_pages/university.html.erb
<div class="col">
      <h2 dir = "rtl">نمونه سؤالات:</h2>
      
      <a class = "link" <%= link_to "حقوق اساسی ۱",    image_path('baseatest.pdf') %><br><br>
      <a class = "link" <%= link_to "حقوق اساسی ۲",    image_path('basebtest.pdf') %><br><br>
      <a class = "link" <%= link_to "حقوق اداری ۱",    image_path('officeatest.pdf') %><br><br>
      <a class = "link" <%= link_to "حقوق اداری ۲",    image_path('officebtest.pdf') %><br><br>
      <a class = "link" <%= link_to "حقوق کار",        image_path('worktest.pdf') %><br><br>
            
       </div>
       
       
    <div class="col">
      <h2 dir = "rtl">منابع:</h2>
          <a class = "link" <%= link_to "حقوق اساسی ۱،۲",    base_path %><br><br>
          <a class = "link" <%= link_to "حقوق اداری ۱،۲",    office_path %><br><br>
      	  
      		<a class = "link" <%= link_to "حقوق کار",   work_path %><br><br>
          <a class = "link" <%= link_to "مقالات",   article_path %></div>


    <div class="col last">
      <h2 dir = "rtl">سر فصل دروس:</h2>
     
      	 <a class = "link" <%= link_to "حقوق اساسی ۱",    basea_path %><br><br>
      	 	<a class = "link" <%= link_to "حقوق اساسی ۲",    baseb_path %><br><br>
            <a class = "link" <%= link_to "حقوق اداری ۱",    officea_path %><br><br>
        <a class = "link" <%= link_to "حقوق اداری ۲",    officeb_path %><br><br>
      		<a class = "link" <%= link_to "حقوق کار",   worka_path %><br>
      
        </div>
    <div class="clr"></div>
  </div>
    <div class="clr"></div>
  </div>